
void OutPut();
void SetMaze();
void CreateBomb();
void MoveLeft();
void MoveRight();
void MoveUp();
void MoveDown();
void Fire();
void MovePlayer(char cInput);
void arrowMove();
void stagePlus();
void openDoor();
void title();
void titleIcon();
void titlePicture();
void speakerPlus();
void speakerMinus();
void mute(); // 효과음 mute
void statusOff();
void playerInform(); 
void tutorial(char input);
void stageSelect();
void selectIcon();
void selectOpption();
void selectPrint(char input);
void titleSpace();
void ranking();
void speedSetting(); // 미세한 Sleep조절
void speedShow(); // show

void playerPos(); //개발 함수
void status(); // 개발 함수 on off button 9번
void cheat(); // 개발자 전용 0번
